apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-foundation-template
  title: AWS Foundation Terraform v2
  description: Cria um novo repositório baseado no AWS Foundation Terraform.
spec:
  owner: team-devops
  type: service

  parameters:
    - title: Informações do Projeto
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Nome do Projeto
          type: string
          description: Nome do novo repositório que será criado.
          ui:field: EntityNamePicker
        description:
          title: Descrição
          type: string
          description: Breve descrição do projeto.
        owner:
          title: Dono
          type: string
          description: Proprietário do repositório.
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Escolha um repositório
      required:
        - repoUrl
      properties:
        repoUrl:
          title: URL do Repositório
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-template
      name: Copiando Código do AWS Foundation
      action: fetch:template
      input:
        url: ./https://github.com/rantonicci/nttdata-ccoe-backstage-aws-foundation/archive/main.zip
        targetPath: ./workspace
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publicando Código no Repositório
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: Este é o repositório do projeto ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Registrando no Catálogo do Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repositório Criado
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Abrir no Catálogo
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
